### ISSUE TITLE
I want to use your mods

### ISSUE THREAD

**Issue by ghost** [CR-019/CNC#1]
I want to use your mods `CNC` to include in my mods.
我想在我的模组里包含CNC模组。我会添加版权说明的。

**Comment by CR-019** [comment]
可以。感谢您对CNC的支持。



在 2021-11-05 19:25:03，"谢哲源" ***@***.***> 写道：

I want to use your mods CNC to include in my mods.
我想在我的模组里包含CNC模组。我会添加版权说明的。

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
